<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_Label', 'doctrine');

/**
 * BaseLUM_Label
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $labelid
 * @property integer $categoryid
 * @property string $websiteurl
 * @property string $imageurl
 * @property string $categoryuri
 * @property string $sidebarhtml
 * 
 * @method integer   getLabelid()     Returns the current record's "labelid" value
 * @method integer   getCategoryid()  Returns the current record's "categoryid" value
 * @method string    getWebsiteurl()  Returns the current record's "websiteurl" value
 * @method string    getImageurl()    Returns the current record's "imageurl" value
 * @method string    getCategoryuri() Returns the current record's "categoryuri" value
 * @method string    getSidebarhtml() Returns the current record's "sidebarhtml" value
 * @method LUM_Label setLabelid()     Sets the current record's "labelid" value
 * @method LUM_Label setCategoryid()  Sets the current record's "categoryid" value
 * @method LUM_Label setWebsiteurl()  Sets the current record's "websiteurl" value
 * @method LUM_Label setImageurl()    Sets the current record's "imageurl" value
 * @method LUM_Label setCategoryuri() Sets the current record's "categoryuri" value
 * @method LUM_Label setSidebarhtml() Sets the current record's "sidebarhtml" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_Label extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_Label');
        $this->hasColumn('labelid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('categoryid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('websiteurl', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imageurl', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('categoryuri', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sidebarhtml', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}