<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_UserFieldPerms', 'doctrine');

/**
 * BaseLUM_UserFieldPerms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userfieldpermid
 * @property integer $userfielddefid
 * @property integer $roleid
 * @property string $permcode
 * 
 * @method integer            getUserfieldpermid() Returns the current record's "userfieldpermid" value
 * @method integer            getUserfielddefid()  Returns the current record's "userfielddefid" value
 * @method integer            getRoleid()          Returns the current record's "roleid" value
 * @method string             getPermcode()        Returns the current record's "permcode" value
 * @method LUM_UserFieldPerms setUserfieldpermid() Sets the current record's "userfieldpermid" value
 * @method LUM_UserFieldPerms setUserfielddefid()  Sets the current record's "userfielddefid" value
 * @method LUM_UserFieldPerms setRoleid()          Sets the current record's "roleid" value
 * @method LUM_UserFieldPerms setPermcode()        Sets the current record's "permcode" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_UserFieldPerms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_UserFieldPerms');
        $this->hasColumn('userfieldpermid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('userfielddefid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('roleid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('permcode', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'NONE',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}