<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_CommentHas_LUM_Entity', 'doctrine');

/**
 * BaseLUM_CommentHas_LUM_Entity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $commentid
 * @property integer $entityid
 * @property string $entitytype
 * @property LUM_Comment $LUM_Comment
 * 
 * @method integer                   getCommentid()   Returns the current record's "commentid" value
 * @method integer                   getEntityid()    Returns the current record's "entityid" value
 * @method string                    getEntitytype()  Returns the current record's "entitytype" value
 * @method LUM_Comment               getLUMComment()  Returns the current record's "LUM_Comment" value
 * @method LUM_CommentHas_LUM_Entity setCommentid()   Sets the current record's "commentid" value
 * @method LUM_CommentHas_LUM_Entity setEntityid()    Sets the current record's "entityid" value
 * @method LUM_CommentHas_LUM_Entity setEntitytype()  Sets the current record's "entitytype" value
 * @method LUM_CommentHas_LUM_Entity setLUMComment()  Sets the current record's "LUM_Comment" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_CommentHas_LUM_Entity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_Comment_has_LUM_Entity');
        $this->hasColumn('commentid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entityid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entitytype', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LUM_Comment', array(
             'local' => 'commentid',
             'foreign' => 'commentid'));
    }
}