<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_Project', 'doctrine');

/**
 * BaseLUM_Project
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $projectid
 * @property integer $categoryid
 * @property integer $categoryparentid
 * @property string $projecttype
 * @property string $websiteurl
 * @property string $imageurl
 * @property string $categoryuri
 * @property string $sidebarhtml
 * 
 * @method integer     getProjectid()        Returns the current record's "projectid" value
 * @method integer     getCategoryid()       Returns the current record's "categoryid" value
 * @method integer     getCategoryparentid() Returns the current record's "categoryparentid" value
 * @method string      getProjecttype()      Returns the current record's "projecttype" value
 * @method string      getWebsiteurl()       Returns the current record's "websiteurl" value
 * @method string      getImageurl()         Returns the current record's "imageurl" value
 * @method string      getCategoryuri()      Returns the current record's "categoryuri" value
 * @method string      getSidebarhtml()      Returns the current record's "sidebarhtml" value
 * @method LUM_Project setProjectid()        Sets the current record's "projectid" value
 * @method LUM_Project setCategoryid()       Sets the current record's "categoryid" value
 * @method LUM_Project setCategoryparentid() Sets the current record's "categoryparentid" value
 * @method LUM_Project setProjecttype()      Sets the current record's "projecttype" value
 * @method LUM_Project setWebsiteurl()       Sets the current record's "websiteurl" value
 * @method LUM_Project setImageurl()         Sets the current record's "imageurl" value
 * @method LUM_Project setCategoryuri()      Sets the current record's "categoryuri" value
 * @method LUM_Project setSidebarhtml()      Sets the current record's "sidebarhtml" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_Project extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_Project');
        $this->hasColumn('projectid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('categoryid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('categoryparentid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('projecttype', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('websiteurl', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imageurl', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('categoryuri', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sidebarhtml', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}