<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_Style', 'doctrine');

/**
 * BaseLUM_Style
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $styleid
 * @property integer $authuserid
 * @property string $name
 * @property string $url
 * @property string $previewimage
 * 
 * @method integer   getStyleid()      Returns the current record's "styleid" value
 * @method integer   getAuthuserid()   Returns the current record's "authuserid" value
 * @method string    getName()         Returns the current record's "name" value
 * @method string    getUrl()          Returns the current record's "url" value
 * @method string    getPreviewimage() Returns the current record's "previewimage" value
 * @method LUM_Style setStyleid()      Sets the current record's "styleid" value
 * @method LUM_Style setAuthuserid()   Sets the current record's "authuserid" value
 * @method LUM_Style setName()         Sets the current record's "name" value
 * @method LUM_Style setUrl()          Sets the current record's "url" value
 * @method LUM_Style setPreviewimage() Sets the current record's "previewimage" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_Style extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_Style');
        $this->hasColumn('styleid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('authuserid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('previewimage', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}