<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_UserBookmark', 'doctrine');

/**
 * BaseLUM_UserBookmark
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userid
 * @property integer $discussionid
 * 
 * @method integer          getUserid()       Returns the current record's "userid" value
 * @method integer          getDiscussionid() Returns the current record's "discussionid" value
 * @method LUM_UserBookmark setUserid()       Sets the current record's "userid" value
 * @method LUM_UserBookmark setDiscussionid() Sets the current record's "discussionid" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_UserBookmark extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_UserBookmark');
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('discussionid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}