<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_Notify', 'doctrine');

/**
 * BaseLUM_Notify
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $notifyid
 * @property integer $userid
 * @property string $method
 * @property integer $selectid
 * 
 * @method integer    getNotifyid() Returns the current record's "notifyid" value
 * @method integer    getUserid()   Returns the current record's "userid" value
 * @method string     getMethod()   Returns the current record's "method" value
 * @method integer    getSelectid() Returns the current record's "selectid" value
 * @method LUM_Notify setNotifyid() Sets the current record's "notifyid" value
 * @method LUM_Notify setUserid()   Sets the current record's "userid" value
 * @method LUM_Notify setMethod()   Sets the current record's "method" value
 * @method LUM_Notify setSelectid() Sets the current record's "selectid" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_Notify extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_Notify');
        $this->hasColumn('notifyid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('method', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('selectid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}