<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_PollData', 'doctrine');

/**
 * BaseLUM_PollData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $polldataid
 * @property integer $pollid
 * @property string $name
 * @property integer $votes
 * 
 * @method integer      getPolldataid() Returns the current record's "polldataid" value
 * @method integer      getPollid()     Returns the current record's "pollid" value
 * @method string       getName()       Returns the current record's "name" value
 * @method integer      getVotes()      Returns the current record's "votes" value
 * @method LUM_PollData setPolldataid() Sets the current record's "polldataid" value
 * @method LUM_PollData setPollid()     Sets the current record's "pollid" value
 * @method LUM_PollData setName()       Sets the current record's "name" value
 * @method LUM_PollData setVotes()      Sets the current record's "votes" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_PollData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_PollData');
        $this->hasColumn('polldataid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pollid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('votes', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}