<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_PollRoleBlock', 'doctrine');

/**
 * BaseLUM_PollRoleBlock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pollid
 * @property integer $roleid
 * @property enum $blocked
 * 
 * @method integer           getId()      Returns the current record's "id" value
 * @method integer           getPollid()  Returns the current record's "pollid" value
 * @method integer           getRoleid()  Returns the current record's "roleid" value
 * @method enum              getBlocked() Returns the current record's "blocked" value
 * @method LUM_PollRoleBlock setId()      Sets the current record's "id" value
 * @method LUM_PollRoleBlock setPollid()  Sets the current record's "pollid" value
 * @method LUM_PollRoleBlock setRoleid()  Sets the current record's "roleid" value
 * @method LUM_PollRoleBlock setBlocked() Sets the current record's "blocked" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_PollRoleBlock extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_PollRoleBlock');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('pollid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('roleid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('blocked', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '1',
              1 => '0',
             ),
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}