<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_CatalogItems', 'doctrine');

/**
 * BaseLUM_CatalogItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $discussionid
 * @property string $imageurl
 * @property integer $price
 * 
 * @method integer          getDiscussionid() Returns the current record's "discussionid" value
 * @method string           getImageurl()     Returns the current record's "imageurl" value
 * @method integer          getPrice()        Returns the current record's "price" value
 * @method LUM_CatalogItems setDiscussionid() Sets the current record's "discussionid" value
 * @method LUM_CatalogItems setImageurl()     Sets the current record's "imageurl" value
 * @method LUM_CatalogItems setPrice()        Sets the current record's "price" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_CatalogItems extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_CatalogItems');
        $this->hasColumn('discussionid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('imageurl', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('price', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}