<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_DiscussionHasTags', 'doctrine');

/**
 * BaseLUM_DiscussionHasTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $discussionid
 * @property integer $tagid
 * @property timestamp $created
 * 
 * @method integer               getDiscussionid() Returns the current record's "discussionid" value
 * @method integer               getTagid()        Returns the current record's "tagid" value
 * @method timestamp             getCreated()      Returns the current record's "created" value
 * @method LUM_DiscussionHasTags setDiscussionid() Sets the current record's "discussionid" value
 * @method LUM_DiscussionHasTags setTagid()        Sets the current record's "tagid" value
 * @method LUM_DiscussionHasTags setCreated()      Sets the current record's "created" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_DiscussionHasTags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_DiscussionHasTags');
        $this->hasColumn('discussionid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tagid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}