<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_DiscussionTags', 'doctrine');

/**
 * BaseLUM_DiscussionTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tagid
 * @property string $tag
 * 
 * @method integer            getTagid() Returns the current record's "tagid" value
 * @method string             getTag()   Returns the current record's "tag" value
 * @method LUM_DiscussionTags setTagid() Sets the current record's "tagid" value
 * @method LUM_DiscussionTags setTag()   Sets the current record's "tag" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_DiscussionTags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_DiscussionTags');
        $this->hasColumn('tagid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tag', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}