<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_Entity_Place', 'doctrine');

/**
 * BaseLUM_Entity_Place
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $entityplaceid
 * @property string $name
 * @property string $address
 * @property string $city
 * @property string $country
 * 
 * @method integer          getEntityplaceid() Returns the current record's "entityplaceid" value
 * @method string           getName()          Returns the current record's "name" value
 * @method string           getAddress()       Returns the current record's "address" value
 * @method string           getCity()          Returns the current record's "city" value
 * @method string           getCountry()       Returns the current record's "country" value
 * @method LUM_Entity_Place setEntityplaceid() Sets the current record's "entityplaceid" value
 * @method LUM_Entity_Place setName()          Sets the current record's "name" value
 * @method LUM_Entity_Place setAddress()       Sets the current record's "address" value
 * @method LUM_Entity_Place setCity()          Sets the current record's "city" value
 * @method LUM_Entity_Place setCountry()       Sets the current record's "country" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_Entity_Place extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_Entity_Place');
        $this->hasColumn('entityplaceid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}