<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_Event', 'doctrine');

/**
 * BaseLUM_Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $discussionid
 * @property date $date
 * @property string $city
 * @property string $country
 * @property Doctrine_Collection $LUM_Discussion
 * 
 * @method integer             getDiscussionid()   Returns the current record's "discussionid" value
 * @method date                getDate()           Returns the current record's "date" value
 * @method string              getCity()           Returns the current record's "city" value
 * @method string              getCountry()        Returns the current record's "country" value
 * @method Doctrine_Collection getLUMDiscussion()  Returns the current record's "LUM_Discussion" collection
 * @method LUM_Event           setDiscussionid()   Sets the current record's "discussionid" value
 * @method LUM_Event           setDate()           Sets the current record's "date" value
 * @method LUM_Event           setCity()           Sets the current record's "city" value
 * @method LUM_Event           setCountry()        Sets the current record's "country" value
 * @method LUM_Event           setLUMDiscussion()  Sets the current record's "LUM_Discussion" collection
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_Event extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_Event');
        $this->hasColumn('discussionid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LUM_Discussion', array(
             'local' => 'discussionid',
             'foreign' => 'discussionid'));
    }
}