<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LUM_UserDiscussionWatch', 'doctrine');

/**
 * BaseLUM_UserDiscussionWatch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userid
 * @property integer $discussionid
 * @property integer $countcomments
 * @property timestamp $lastviewed
 * 
 * @method integer                 getUserid()        Returns the current record's "userid" value
 * @method integer                 getDiscussionid()  Returns the current record's "discussionid" value
 * @method integer                 getCountcomments() Returns the current record's "countcomments" value
 * @method timestamp               getLastviewed()    Returns the current record's "lastviewed" value
 * @method LUM_UserDiscussionWatch setUserid()        Sets the current record's "userid" value
 * @method LUM_UserDiscussionWatch setDiscussionid()  Sets the current record's "discussionid" value
 * @method LUM_UserDiscussionWatch setCountcomments() Sets the current record's "countcomments" value
 * @method LUM_UserDiscussionWatch setLastviewed()    Sets the current record's "lastviewed" value
 * 
 * @package    admin-incongrue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLUM_UserDiscussionWatch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LUM_UserDiscussionWatch');
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('discussionid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('countcomments', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('lastviewed', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}