<?php

/**
 * PluginLUM_ZeitgeistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_ZeitgeistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_ZeitgeistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Zeitgeist');
    }
}