<?php

/**
 * PluginLUM_RoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_RoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_RoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Role');
    }
}