<?php

/**
 * PluginLUM_CategoryRoleBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_CategoryRoleBlockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_CategoryRoleBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_CategoryRoleBlock');
    }
}