<?php

/**
 * PluginLUM_ProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_ProjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_ProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Project');
    }
}