<?php

/**
 * PluginLUM_PollRoleBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_PollRoleBlockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_PollRoleBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_PollRoleBlock');
    }
}