<?php

/**
 * PluginLUM_EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Event');
    }
}