<?php

/**
 * PluginLUM_DiscussionTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_DiscussionTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_DiscussionTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_DiscussionTags');
    }
}