<?php

/**
 * PluginLUM_DiscussionHasTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_DiscussionHasTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_DiscussionHasTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_DiscussionHasTags');
    }
}