<?php

/**
 * PluginLUM_CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Category');
    }
}