<?php

/**
 * PluginLUM_DiscussionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_DiscussionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_DiscussionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Discussion');
    }
}