<?php

/**
 * PluginLUM_UserFieldDefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_UserFieldDefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_UserFieldDefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_UserFieldDef');
    }
}