<?php

/**
 * PluginLUM_IpHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_IpHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_IpHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_IpHistory');
    }
}