<?php

/**
 * PluginLUM_CommentHas_LUM_EntityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_CommentHas_LUM_EntityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_CommentHas_LUM_EntityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_CommentHas_LUM_Entity');
    }
}