<?php

/**
 * PluginLUM_StyleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_StyleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_StyleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Style');
    }
}