<?php

/**
 * PluginLUM_NotifiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_NotifiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_NotifiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Notifi');
    }
}