<?php

/**
 * PluginLUM_UserFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_UserFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_UserFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_UserField');
    }
}