<?php

/**
 * PluginLUM_CatalogItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_CatalogItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_CatalogItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_CatalogItems');
    }
}