<?php

/**
 * PluginLUM_CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_CommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Comment');
    }
}