<?php

/**
 * PluginLUM_PollBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_PollBlockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_PollBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_PollBlock');
    }
}