<?php

/**
 * PluginLUM_CategoryBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_CategoryBlockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_CategoryBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_CategoryBlock');
    }
}