<?php

/**
 * PluginLUM_LabelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_LabelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_LabelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Label');
    }
}