<?php

/**
 * PluginLUM_Entity_PlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_Entity_PlaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_Entity_PlaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Entity_Place');
    }
}