<?php

/**
 * PluginLUM_UserBookmarkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_UserBookmarkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_UserBookmarkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_UserBookmark');
    }
}