<?php

/**
 * PluginLUM_UserFieldPermsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_UserFieldPermsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_UserFieldPermsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_UserFieldPerms');
    }
}