<?php

/**
 * PluginLUM_NotifyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_NotifyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_NotifyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Notify');
    }
}