<?php

/**
 * PluginLUM_AttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_AttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_AttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Attachment');
    }
}