<?php

/**
 * PluginLUM_PollDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_PollDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_PollDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_PollData');
    }
}