<?php

/**
 * PluginLUM_UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_User');
    }
}