<?php

/**
 * PluginLUM_PollTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_PollTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_PollTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_Poll');
    }
}