<?php

/**
 * PluginLUM_DiscussionUserWhisperFromTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLUM_DiscussionUserWhisperFromTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLUM_DiscussionUserWhisperFromTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLUM_DiscussionUserWhisperFrom');
    }
}